name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.2.2' }
          - { os: windows-2022, r: '4.2.2' }
          - { os: macOS-latest, r: '4.2.2' }

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: '4.2.2'  # Windows专用，明确指定rtools版本

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'devtools'), repos='https://cloud.r-project.org')"
          Rscript -e "tryCatch(remotes::install_deps(dependencies=TRUE), error=function(e) message('依赖安装错误: ', e$message))"

      - name: Check package
        run: |
          R CMD check --no-manual --as-cran .
